apiVersion: 1
datasources:
  - name: vehicle-influx
    type: influxdb
    access: proxy
    url: http://localhost:8086
    jsonData:
      version: Flux
      organization: home
      defaultBucket: vehicle
    secureJsonData:
      token: ${INFLUX_TOKEN}
